### ISSUE TITLE
Naming convention of the valve foot prints

### ISSUE THREAD

**Issue by Misca1234** [KiCad/kicad-footprints#1103]
I am scripting the valve foot prints, the ambition is to replace the existing foot prints with new ones

My intention is to fix the foot prints then the 3D models and then update the symbols

But I want some consensus about the names of the foot prints
Valve_Magnoval_B9D-9_D30.00mm_P17.45mm_A36_RP.kicad_mod

where 
Valve is the function
Magnoval_B9D is the "serie"
9 is the number of pins
D30.00mm says it is 30 mm
P17.45mm defines the diameter of the circle where the pins are placed
A36 Says that the angle between the pins is 36 degree
RP points to round pins (there is oval pins as well)

The foot print will always assume that there will be possible to place the tube directly onto the pcb or via  socket and in those cases where the tube have a spigot, it will be mounted in a socket.

The sockets I have currently chosen are
Magnoval_B9D
Noval_B9A
Miniature_B7G
Loctal_B9G
Loctal_B8G
Decar_B10G
Octal_K8A

Or should we just name them as
Valve_Magnoval_B9D_RP.kicad_mod

https://en.wikipedia.org/wiki/Tube_socket

They , kinda look like this now

![bild](https://user-images.githubusercontent.com/25547797/48873225-1a5af200-eded-11e8-9a6f-a0d3e330bc52.png)

![bild](https://user-images.githubusercontent.com/25547797/48873231-2941a480-eded-11e8-9124-8cb71d492541.png)

**Comment by Misca1234** [comment]
If no one objects I will name them like this 

Foot prints
Valve_ZZZZZZZ-XX-YYYYY

3D models of sockets
Valve_Socket_ZZZZZZZ-XX-YYYYY_AAAA

3D model of tubes
Valve_Tube_ZZZZZZZ-XX

ZZ is an arbitary string such as  'Magnoval' or 'BELTRON_VTPCX_9'
XX will be real identifier used in the foot print filter, such as 'K9A, 'M10G'

AAAA will be a string like this "D13.00mm_TTT'
Where D13.00 describe the diameter of the circle on which the holes are placed
TTT Can be 'Pin', 'Ear' 'Pigs'
to distinguish the type of pin, like these
http://belton.co.kr/inc/downfile.php?seq=58&file=pdf

So the standard B9G will be named
FP:    Valve_Loctal-B9G-D21.00mm_Pin.kicad_mod
3D model of socket:    Valve_Socket_Loctal-B9G-D21.00mm_Pin.kicad_mod
3D model of tube:    Valve_Tube_Loctal-B9G-D21.00mm_Pin.kicad_mod

![bild](https://user-images.githubusercontent.com/25547797/48958904-4946a480-ef62-11e8-819c-0454144e5139.png)

![bild](https://user-images.githubusercontent.com/25547797/48958914-56fc2a00-ef62-11e8-931e-0ce4e184a441.png)

**Comment by Misca1234** [comment]
Closing, see push
https://github.com/KiCad/kicad-footprints/pull/1111

**Comment by Misca1234** [comment]
Closing, see push
https://github.com/KiCad/kicad-footprints/pull/1111

**Comment by evanshultz** [comment]
I like the simplified naming scheme since, if the manufacturer and tube type define the pin layout, other information is superfluous.

Three things to note:
1. I believe you should put underscores between sections, so `BELTRON_VTPCX_9` should be `BELTRON-VTPCX-9`.
1. The footprint filter should probably start with `Valve` for best matching.
1. Why would the footprint and (valve) model not have the same name? They match and the valve could be soldered directly to the PCB. Adding `_Socket` to the end could indicate the socket's 3D model and would also match all the preceding footprint filter so picking socket or not-socket in CvPcb is easier.

**Comment by Misca1234** [comment]
The XX uniquely identify the foot print (and therefore the socket), that is, in the foot print name
Valve_Loctal-B9G-D21.00mm_Pin.kicad_mod

Valve_Loctal D21.00mm_Pin is really not needed, so the foot print filter will be `*B9G*` or `Valve*B9G*`
The diameter is needed to distinguish different sockets form each other unless the manufacture series identify it.


> Why would the footprint and (valve) model not have the same name? They match and the valve could be soldered directly to the PCB. 

> Why would the footprint and (valve) model not have the same name?

The valve is only extra candy, the "important" thing is the socket


I was thinking of this but I do not believe that anyone will solder vacuum tubes directly to the PCB because they break down more often than, say a transistor, however the foot prints I made is for sockets that is 1:1 to the valve or soldering the tube directly to the pcb.
Currently the The 3D models is jsut to show more graphics, it is only the belton one that is a "true" socket

Currently the end is pin or tap to distinguish between 
http://www.belton.co.kr/upload/photo/photo_1476681172.JPG
http://www.belton.co.kr/upload/photo/photo_1476085686.JPG

and even perhaps 'ear' for 
https://i.ebayimg.com/images/g/TWIAAOSwygJXggyN/s-l300.jpg

**Comment by Misca1234** [comment]
Btw
When point have meged my foot print script I will update it with some extra fetures so we can make sockets like this

![bild](https://user-images.githubusercontent.com/25547797/49044882-72b83800-f1cf-11e8-8cfe-07d382b73954.png)

**Comment by Misca1234** [comment]
Let try this, Belton do one socket of the B9A type, it's name is VT9-PT
http://www.belton.co.kr/inc/downfile.php?seq=58&file=pdf

If we name the naked foot print to 
Valve_Noval-B9A_BELTON-VT9-PT.kicad_mod

The foot print with 3D models
Valve_Noval-B9A_BELTON-VT9-PT_Socket.kicad_mod

The 3D model of the tube can be named 
Valve_Tube_Noval-B9A-D11.89mm_Pin

Then the FP filter can be 
Valve_Noval-B9A*
Which catch both the "naked" foot print and those with 3D models but not the 3D model of the tube

**Comment by evanshultz** [comment]
I think we should settle on "tube" vs "valve". You're using both terms above but the official library now has a library named Valve. So the usage of "tube" above is not intentional, right?

I'm a bit confused by the above and I think it may just be typos. Let me re-write it and please let me know if the below is correct.

If we name the naked foot print to
Valve_Noval-B9A`(_BELTON-VT9-PT)`.kicad_mod

The foot print with `(3D models) socket`
Valve_Noval-B9A_Belton-VT9-PT_Socket.kicad_mod

The 3D model of the socket can be named
Valve`(_Tube)`_`Belton`-B9A_Socket.wrl

The 3D model of the tube can be named
Valve`(_Tube)`_Noval-B9A.wrl

Then the FP filter can be
Valve`*`Noval`*`B9A*

A few things I think about reading through this:
1. The combined 3D model of the socket and the valve is not above. I assume there should be one so th user can see that. It will be a single model name like the second item above, right?
1. Would a nice naming format be `Valve_<valve manufacturer>_<valve MPN>_Socket_<socket manufacturer>_<socket MPN>`. This is essentially moving the work `Socket` up so it's like a divider between the valve info and socket info.
1. We want a generic valve symbol that doesn't care about the socket. A footprint in 5.1 can support multiple 3D models all together, so the same valve footprint could be reused and combined with various sockets (each socket + valve combination would need a unique footprint). That would require the valve Z offset to not be zero which, if we go that route, requires a KLC adjustment.
1. The official library is not going to capture every single socket. If the bare tube is provided, at least that's a starting point for users. If there are a few socket options for each valve then we probably have good coverage and hopefully more PRs fill in the gaps later. How do you decide what sockets to include?

**Comment by Misca1234** [comment]
> I assume there should be one so th user can see that. It will be a single model name like the second item above, right?

The idea was to combine two different 3D models, not make one 3D model that includes both a socket and a valve.

> Valve_<valve manufacturer>_<valve MPN>_Socket_<socket manufacturer>_<socket MPN>. 

I think that would be a bad idea

> The 3D model of the socket can be named
> Valve(_Tube)_Belton-B9A_Socket.wrl

A specific socket, such as Noval-B9A is not for a specific tube, many tubes fits that socket.

> The official library is not going to capture every single socket. 
> How do you decide what sockets to include?

It is a mix of the existing ones, what is said on https://en.wikipedia.org/wiki/Tube_socket about which ones that are still in use and I tries to get some feedback from the users at https://www.radiomuseum.org

It is difficult to find any manufactures of the ordinary valve socket, such as 
https://www.conrad.com/ce/en/product/130552/Vacuum-Tube-Valve-Holder-Base-Magnoval-Fitting-type-details-PCB-Description-Ceramic?ref=searchDetail

Belton is essential the only one I found. When I asked http://audionote.co.uk they said that the manufacture of the socket they sold was no longer producing them. I have not got a response from https://www.conrad.com/ce/ yet, who makes the socket they sell.

I think it would be enough to name the sockets as 
Valve_<valve MPN>_<valve manufacturer>_Socket.kicad_mod
Valve_<valve MPN>_<valve manufacturer>_<valve MPN>_Socket.wrl/.step
an example
Valve_Noval-B9A_Belton-VT9-PT-C_Socket.kicad_mod
These foot prints will have a dummy 3D model of a tube on top of them

and the symbol
<valve MPN>

There is really no point to have specific 3D models of a specific tube, no one solder them directly to the PCB

**Comment by Misca1234** [comment]
After been corresponding on radiomuseum wit ha guy
https://www.radiomuseum.org/forum/seeking_help_with_foot_prints_in_kicad.html?thread_id=500265

It essential boils down to this.

1. Having footprint's for soldering tubes directly to PCB is near pointless due to the heat that the valve produce, it will affect the pcb to much and sucks to replace.

2. Having PCB sockets is a somewhat bad idea due to heat produced by the valves and the force needed to insert the tubes into the sockets (breaking copper lines on the PCB etc.), the guy in the thread already encountered this problem during the 1960's.

3. There is really no standard around the sockets anyway, so the designer of the PCB is left to use sockets that is highly manufacture specific and might be available over a longer time.

4. Overall recommendation is to use panel mount sockets and then connect the valve via wires to an ordinary contact to the PCB.

5. It is way more important to have the symbols in order and then leave the decision up to the designer on how to connect the valve (from the panel socket) to the PCB.

I will make some manufacture specific foot prints just so KiCad have some and then spend time on the symbols. The issue of how to name the foot prints etc. is a minor issue because it will never "take off".
