### ISSUE TITLE
Closed solder jumpers give DRC errors

### ISSUE THREAD

**Issue by matthijskooijman** [KiCad/kicad-footprints#1165]
The current closed solder jumper footprints contain a custom-shaped pad, that includes the bridge to another pad. This approach gives pad-near-pad errors for the overlapping pads, and pad-near-track for the tracks connected to the pads (at least for the track connected to the pad *without* bridge, since that touches the pad *with* bridge).

e.g.:

![image](https://user-images.githubusercontent.com/194491/49991179-8d84fd80-ff80-11e8-8452-5b2fb25f52ee.png)

Here pad 1 has the bridge attached.

This issue was previously mentioned [here on the list](https://lists.launchpad.net/kicad-developers/msg36445.html) and 
[here on github](https://github.com/KiCad/kicad-footprints/pull/716#issuecomment-404928947).

A possible solution seems to be to remove the bridge from the pad, and instead use a graphic polygon on the copper layer. That will at least fix the DRC errors, and I *think* it should result in the same gerbers. I risk is that in the future, DRC might be adapted to include graphic polygons in its reasoning, perhaps.

The workaround suggested by the list post above is to use an open schematic symbol and footprint and connect these manually. This is of course less elegant, but also means that both sides of the solder jumper become the same net, so it is then easy to accidentally connect something to the wrong side of the jumper, without DRC noticing, which seems like a signifcant problem.

**Comment by evanshultz** [comment]
Thanks for surfacing this issue!

I'm not one of the developers, but I would think any object on a copper layer should be considered by the DRC engine. Everything on a copper layer should be part of all copper-to-whatever DRC checks.

Adding connection on the copper layer manually is a hack. Most ECAD tools of which I'm aware have progressed beyond this by now. Not having connectivity match between the circuit board and the IPC-356 netlist is a pain. It does not matter how this is annotated on the fab drawing or other documentation, you will get questions or continuity check failures which are bogus. And it will keep coming up even with the same PCB vendors. Multiple vendors. It never ends. This is why some ECAD tools have specific net shorting features that can capture this connectivity and place it in the IPC-356 netlist for the board house to do continuity checks again. (Though even then you can still have annoying issues with PCB vendors.) The moral is that somehow the netlist and PCB should match in connectivity. If KiCad is limited at this time and doesn't allow nice net shorting, then what is the best interim solution? Maybe this is it. I don't personally think it's a bad way to go until KiCad adds a reasonable net shorting solution.

I would suggest checking the Gerbers before making this proposal instead of leaving it open. This is obviously crucial. I made a simple project and have attached it here. For ease of review, below you will find screenshots of the schematic, board in KiCad, board DRC errors, and the resulting Gerber:
![image](https://user-images.githubusercontent.com/1936989/50106963-2b9af100-0229-11e9-803f-9e506e3ec3f9.png)
![image](https://user-images.githubusercontent.com/1936989/50107255-0fe41a80-022a-11e9-9f63-a3d90114bf58.png)
![image](https://user-images.githubusercontent.com/1936989/50107267-183c5580-022a-11e9-81c1-b576c2051a12.png)
![image](https://user-images.githubusercontent.com/1936989/50107246-ffcc3b00-0229-11e9-8dfc-98e1cac16275.png)

In addition, I find that I'm unable to start routing from the shorted pad on the bridged jumpers in our library as they are now (and routing to it is wonky as well, apparently because the routing engine knows they're different nets?). That seems like a pretty significant problem. Did you see that also?

Lastly, the footprint filters for the jumper symbols are broken. They are `Jumper*` while all the footprints are `SolderJumper_...`. Sigh.

**Comment by evanshultz** [comment]
Please let me know if this is capturing the issue you noticed and if there are some other caveats to consider.

**Comment by matthijskooijman** [comment]
Agreed that capturing the internal connection would be the best solution. However, care should be taken to not see this as a normal wire connection, which would create a single net that connects through the jumper, but instead know that these two nets are connected inside the jumper.

Looking at your example, I believe that does show the issue. I'm a bit surprised, though, that it shows only one DRC error rather than a bunch of them. No time right now to investigate, unfortunately.

**Comment by evanshultz** [comment]
Showing shorts in the IPC-356 netlist is what I've used to indicate that separate nets are shorted together, and it seems to work well both for engineers and the PCB suppliers. At least in my experience. (I've also annotated every net short on the fab drawing for clarity.) Here is an excerpt from Allegro:
![image](https://user-images.githubusercontent.com/1936989/50109152-e8438100-022e-11e9-9460-7ded12414190.png)

To get this piece, however, someone would need to develop the feature. And to do that, we would need a consistent way to note an intentional short in the design (so the DRC engine knows it's OK and for the IPC-356 netlist to extract the net short info from). Since this is location-dependent, this would need to be done inside the board editor. While this is a good user suggestion, I've not found this communicate fully with PCB suppliers and there's a notable chunk of work outlined above to get it properly implemented.

Perhaps the number of DRC errors are related to the trace thickness, spacing constraints, etc.?

**Comment by sethhillbrand** [comment]
Hi Folks.  The pad-near-pad errors can be resolved if you use polygons to jumper the pads.  As noted elsewhere, the full fix will require a file format change in v6.  But for v5.1, it would be good if the standard libraries did not include known DRC errors.

**Comment by evanshultz** [comment]
@matthijskooijman 
Did you submit a PR for this? I see a commit above but no PR to the KiCad footprint repo.

**Comment by sethhillbrand** [comment]
Here is a pull request for this item  https://github.com/KiCad/kicad-footprints/pull/1437

**Comment by evanshultz** [comment]
Closing since the PR to address this issue was merged.
