### ISSUE TITLE
Zero orientation of oszillator lib is wrong

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#1264]
The script creating oscillator footprints creates them in the wrong orientation.

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-footprints/issues/155

**Comment by poeschlr** [comment]
The issue you linked is about polarity markers not about the zero orientation. Are you sure this is a duplicate? (I think the other issue might have already been resolved.)

**Comment by evanshultz** [comment]
The zero orientation was mentioned in the post from the old repo that resulted in #155. Since these will surely be scripted, perhaps one issue is better than multiple? I'll clearly add this to the old issue but if you want to reopen this issue or do something else please go ahead. Sorry if I was too hasty.
