### ISSUE TITLE
Request for SMD 2.54mm Pin headers in Horizontal config

### ISSUE THREAD

**Issue by gcormier** [KiCad/kicad-footprints#1487]
The library is full of every other type it would seem, minus the horizontal SMD configuration.

![image](https://user-images.githubusercontent.com/8388983/54573717-d6a37e00-49c3-11e9-916f-55e38c1f0d29.png)

Trying to get python scripting going has been failure for me. Would anyone consider churning out a bunch of these?

TSM-106-01-T-SH
![image](https://user-images.githubusercontent.com/8388983/54573769-fdfa4b00-49c3-11e9-9980-1aa45090f248.png)

**Comment by evanshultz** [comment]
We don't take requests as a rule since that would overwhelm everybody and since our footprint tools are freely-available, but we can help you with scripting. Submit a PR or issue at https://github.com/pointhi/kicad-footprint-generator, tag me if you like, and we'll see what we can do to get you going. It's fun (a nerdy kind of fun) once you're over the hump!

I'm not sure if this is generic and making them manufacturer-specific was wrong, but did you see:
![image](https://user-images.githubusercontent.com/1936989/54765429-bee01b80-4bb6-11e9-991a-d096f001e21f.png)

**Comment by gcormier** [comment]
Will do!
