### ISSUE TITLE
Keystone 2468 screw holes are backwards

### ISSUE THREAD

**Issue by ianrrees** [KiCad/kicad-footprints#1497]
The footprint has two mounting holes, currently they are in the wrong position.  They are oriented as for mounting the battery pack on the back side of the board, where the rest of the footprint puts the battery pack on the front side.  See http://www.keyelco.com/product-pdf.cfm?p=1033

**Comment by evanshultz** [comment]
Thanks for taking time to report this.

Datasheet:
![image](https://user-images.githubusercontent.com/1936989/54934910-82752e00-4edc-11e9-94fc-83a171359354.png)

Footprint:
![image](https://user-images.githubusercontent.com/1936989/54934814-5d80bb00-4edc-11e9-9ced-64920d14ee57.png)

It looks OK to me, but you have to rotate and orient things correctly since the footprint has the `+` pin at the top left. Can you please clarify?

**Comment by ianrrees** [comment]
Basically, the Y (or X) coordinates of the two mounting holes need to be swapped with each other.

![image](https://user-images.githubusercontent.com/5280982/54947632-a3eb1e00-4f9f-11e9-8b44-28025962a3ce.png)

**Comment by evanshultz** [comment]
Oh. I got it. I didn't catch that this was about the mounting holes. Sorry.

Are you willing to submit a PR to fix this issue?

**Comment by ianrrees** [comment]
I'll make one based on the web client shortly, but didn't do that initially because the last time I've made PRs to KiCad repos, they seem to have gotten caught in a morass of editing and commentary that left me feeling like it was a waste of effort.
