### ISSUE TITLE
DIN41612-B-2x32_horizontal wrong pad names

### ISSUE THREAD

**Issue by sxpert** [KiCad/kicad-footprints#1500]
pad names are labelled a1, a2, a3 ...
while the symbol has A1, A2, A3 ... (and 1A, 2A, 2B...)

**Comment by evanshultz** [comment]
Thanks for taking the time to report an issue you found with the official libraries.

I'm closing this because it's a known issues that's been brought up before. Please try searching in the future before making a new issue.

All DIN 41612 symbols and footprints are planned to be updated, and a whole range of scripted footprints is moving along but didn't make it into v5.1.
