### ISSUE TITLE
SMD Cap 0402 pad size (width) increased in KiCAD 5

### ISSUE THREAD

**Issue by matianfu** [KiCad/kicad-footprints#2377]
I just noticed that in KiCAD 5, pad size of 0402 cap is changed. In KiCAD 4.x, it is 0.6mm by 0.5mm, while in KiCAD 5, it is 0.59mm by 0.64mm. The increased width from 0.5mm to 0.64mm is a disaster for design with compactly arranged capacitors. For example, on the bottom side of a DDR chip or arm processor.

I don't think 0.5mm width 0402 pad is anything dangerous for assemply. It is widely used in mass production. 0.64mm may be better for thermal concern.

So could you please provide a compact or narrow version of SMD caps and resistors. They are important for many consumer electronics design since the board space is usually constrained and that is exactly why 0402 packages are chosen.

**Comment by evanshultz** [comment]
I could search the history to see why the old chip component footprint pads were the way they were, but I'm not going to... since what's important is the lib now.

The current footprints are created from a script at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/SMD_chip_package_rlc-etc. They are to IPC 7351B fillet goals, but with 7351C draft pad shape (rounded rectangle). IPC 7351 is an industry standard and is well-regarded and thus we paid no attention to the current footprints. So we can consider that the pads were undersized before.

However, they're only undersized when compared with the IPC 7351 _nominal_ fillet goals. The script currently only generates nominal footprints, and not most (maximum) or least (minimum) footprints. Smaller pads are useful for a number of uses, such as with various solder pastes and to improve power supply impedance at high frequencies. And bigger pads are helpful when wave soldering chip parts, as one example. Therefore, I have already updated the script to do this and submitted the changes at https://github.com/pointhi/kicad-footprint-generator/pull/439.

But before that is done, the body sizes of chip components need to be corrected. There was an error in the script. I've corrected the script at https://github.com/pointhi/kicad-footprint-generator/pull/438 and pushed updated footprints at https://github.com/KiCad/kicad-footprints/pull/2280. This is blocking the submission of footprints with smaller (and bigger) pads than the library currently contains.

I hope this answers your question and explains things. I believe everything you've written is understood and considered, and the limitation is in manpower to review and merged the updates.
