### ISSUE TITLE
Silkscreen for small footprints eg. 0805, 0603

### ISSUE THREAD

**Issue by dawid-solitech** [KiCad/kicad-footprints#655]
In previous version of footprints library, components like resistors 0805, 0603 have got silkscreen outline. Now in the latest version there is no silkscreen. Why do you often change names, apperance on a pcb? I can't find any EDA where is no silkscreen for these components.

**Comment by Ratfink** [comment]
This change occurred in https://github.com/KiCad/kicad-footprints/pull/469, when we fixed the dimensions of these footprints.  The script that generates them (located [here](https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/SMD_chip_package_rlc-etc)) is overly conservative with silkscreen.  I pointed this out, but merge them anyway because automated assembly would benefit from the correct pad sizes, and removing the silkscreen would only hurt manual assembly, which represents a small fraction of boards produced.  A patch to the script that adds silkscreen back to these footprints would be welcome!

**Comment by poeschlr** [comment]
I will look into that. I fear it will need to violate KLC though.

**Comment by poeschlr** [comment]
The 0805 size is a bit of a trouble maker. The tolerance range for the lead to lead clearance is extremely large. (First i thought IPC is just very conservative with their size definitions. But i looked at some random resistors on farnell. After just a few i had resistors within the full range of the IPC tolerance definition.)

**Comment by poeschlr** [comment]
Fix for this is included in https://github.com/KiCad/kicad-footprints/pull/653

**Comment by poeschlr** [comment]
fix has been merged
