### ISSUE TITLE
Bourns_PTV09A-1 questions

### ISSUE THREAD

**Issue by robkam** [KiCad/kicad-footprints#904]
I'm beginning to draw some potentiometer footprints, while following the KLC and looked at the [Bourns_PTV09A-1](https://github.com/KiCad/kicad-footprints/blob/master/Potentiometer_THT.pretty/Potentiometer_Bourns_PTV09A-1_Single_Vertical.kicad_mod) as an example, there are some aspects I don't understand. 

Aren't pins 1 & 3 mirrored to what's on the data sheet?
KLC F4.2 - Pin 1 should be located at the top left? I suppose it's as close as it can be.
On one of the sides there's no clearance between F.CrtYd and F.Silk?

Also in general, wouldn't plated through be better for the mounting hole, e.g. less chance of pads coming loose during repairs?

**Comment by evanshultz** [comment]
Since you reference the datasheet, it would be helpful to link to it. https://www.bourns.com/docs/Product-Datasheets/PTV09.pdf

Pin numbering:
Yes, but it doesn't matter. What matters is know the relationship between rotating the shaft and the wiper position. This is undefined in KLC now but I wrote up https://github.com/KiCad/kicad-symbols/issues/165 to capture the need to figure this out.

Pin 1 position:
The pot footprint generator script missed this requirement and I recall it being mentioned in a PR or issue I can't find now.

Silk/courtyard clearance:
This doesn't matter and isn't specified anywhere in KLC.

Plated mounting holes:
Yes, I agree they should be plated. They're not really mounting holes if they're unplated.

**Comment by robkam** [comment]
Thanks.
